---
title: Innovent Creative LLC
timezone: America/Chicago
collections:
  careers:
    title: Careers
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:title/"
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: post
    category: work
encoding: utf-8
description: We create events that connect brands to audiences in powerful ways. Every
  service we offer throughout the Event Continuum roadmap is uniquely designed to
  deliver a seamless and integrated story and ultimately, maximize ROI.
baseurl:
url: https://www.goinnovent.com/
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- ".gitignore"
- ".git"
- ".editorconfig"
permalink: "/:title/"
linkedin: https://www.linkedin.com/company-beta/11147866/
twitter: https://twitter.com/GoInnovent
instagram: https://www.instagram.com/goinnovent/
footer_address:
  address1: 1920 N. Coit Road
  address2: Suite 200-167
  city: Richardson
  state: Texas
  zip: 75080
analytics: UA-101614777-1
plugins:
- jekyll-assets
assets:
  sources:
  - _assets/css
  - _assets/js
  autoprefixer:
    browsers:
    - "> 1%"
